stages:
  - test
  - build

variables:
  BUILD_IMAGE_VERSION: latest
  TAG_LOGIC: '(if [ "$${CI_COMMIT_BRANCH}" == "master" ]; then echo "latest"; else echo "$${CI_COMMIT_BRANCH}"; fi);'

run_test:
  stage: test
  image: zenika/alpine-chrome:with-node
  variables:
    NODE_ENV: "test"
  before_script:
    - npm install
  script:
    - npm run test

run_lint:
  stage: test
  image: registry.gitlab.com/picrossr/images/build-image:${BUILD_IMAGE_VERSION}
  before_script:
    - npm install
  script:
    - npm run lint

build_image:
  stage: build
  image: google/cloud-sdk
  variables:
    NODE_ENV: "production"
  script:
    - TAG=$(eval TAG_LOGIC)
    - echo $GCP_SERVICE_KEY > keyfile.json
    - gcloud auth activate-service-account wordsearch@wordsearch-300617.iam.gserviceaccount.com --key-file=keyfile.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud builds submit . --config=cloudbuild.yaml --substitutions=TAG_NAME=$TAG