stages:
  - test

variables:
  BUILD_IMAGE_VERSION: latest

run_test:
  stage: test
  image: zenika/alpine-chrome:with-node
  variables:
    NODE_ENV: "test"
  before_script:
    - npm install
  script:
    - npm run test