stages:
  - test

variables:
  BUILD_IMAGE_VERSION: latest

run_test:
  stage: test
  image: registry.gitlab.com/picrossr/images/build-image:${BUILD_IMAGE_VERSION}
  variables:
    NODE_ENV: "test"
  before_script:
    - npm install
  script:
    - npm run test