name: Main workflow

env:
  TAG_LOGIC: '(if [ "${{ github.REF_NAME }}" == "main" ]; then echo "latest"; else echo "${{ github.sha }}"; fi);'

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:22.14-alpine
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
  
  test:
    runs-on: ubuntu-latest
    container: node:22.14-alpine
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - uses: 'google-github-actions/auth@v2'
      with:
        project_id: ${{ vars.GCP_PROJECT_ID }}
        credentials_json: ${{ secrets.GCP_SERVICE_KEY }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name: Build
      run: |
        TAG=$(eval $TAG_LOGIC)
        echo $TAG
        gcloud builds submit . --config=cloudbuild.yaml --substitutions=TAG_NAME=$TAG,_DESTINATION=${{ vars.GCP_DESTINATION }}

  deploy:
    environment: production
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref_name == 'main'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'google-github-actions/auth@v2'
      with:
        project_id: ${{ vars.GCP_PROJECT_ID }}
        credentials_json: ${{ secrets.GCP_SERVICE_KEY }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name: Deploy
      run: |
        TAG=$(eval $TAG_LOGIC)
        gcloud run deploy client --image ${{ vars.GCP_DESTINATION }}:$TAG --region us-east1 --platform managed

        
